### ISSUE TITLE
Hello from Hiveeyes and Terkin

### ISSUE THREAD

**Issue by amotl** [ElectronicCats/PicoWAN#1]
Dear @sabas1080, @capuchino69 and @wero1414,

we like what you are doing here, so we just added a post about it to [our page about the Raspberry RP2 microcontroller family](https://community.hiveeyes.org/t/raspberry-rp2-microcontroller-family/3777). Also, our ways just crossed at https://github.com/smlng/pycayennelpp/issues/71, thanks for acknowledging my post, @sabas1080.

Attaching to that, we would like to give you a short introduction to the [Terkin Datalogger](https://github.com/hiveeyes/terkin-datalogger) we had been conceiving. It already supports a reasonable number of devices and sensors and we would like to see it finding further adoption beyond its [original use case](https://community.hiveeyes.org/search?q=terkin). Originally conceived by @einsiedlerkrebs and me, the main development happened in 2019/2020 already.

On the LoRaWAN end, it is already based on the excellent [PyCayenneLPP](https://github.com/smlng/pycayennelpp) library by @smlng, so there is no reason to look further ;]. The whole LoRaWAN subsystem has been conceived with tremendous help by @thiasB, which we appreciated very much. While we originally started development on Pycom MicroPython the other day, @poesel also joined us with excellent contributions to bring in compatibility with vanilla MicroPython.

So, to make the story come to an end, we would like to finally start supporting the RP2040 family of devices in general and of course, some of their specific implementations like the PicoWAN. Unfortunately, we don't own such a device yet, but as we see it is quickly gaining traction on various ends, we should finally get hold of one or another.

We hope you liked this little introduction about what we are doing on our end, and, if you are interested, we will let you know as soon as we can find some time to continue the development on the code base and maybe even add specific support for RP2040-based devices or at least for MicroPython 1.14 in general.

Keep up the spirit and with kind regards,
Andreas.

**Comment by sabas1080** [comment]
Dear @amotl 

Thank you for your words, we are interested in collaborating with your projects, we will have prototypes of this project in two weeks.

Thank you for contributing to other Electronic Cats projects  as Cayenne LPP
